# Generated by Django 5.1.7 on 2025-03-15 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_alter_certificate_ipfs_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='is_revoked',
            field=models.BooleanField(default=False),
        ),
    ]
